### ISSUE TITLE
Error when running rmd2md()

### ISSUE THREAD

**Issue by mammykins** [ivyleavedtoadflax/rmd2md#2]
Following the excellent and comprehensive README compilation instructions, I installed the package and ran while in the correct working directory:

``` getwd()
 [1] "C:/Users/mammykins/Documents/GitHub/machinegurning.github.io"

rmd2md::rmd2md()
 Error in value[3L] : 
 Error produced running rmd2md():Error in doTryCatch(return(expr), name, parentenv, handler): Figures directory: figures/ does not exist!
```

Which is strange, as the figures/ directory does appear to exist:

```
list.dirs()[261]
 [1] "./figures"
```

**Comment by ivyleavedtoadflax** [comment]
I've created a fix for this problem. Can you try installing this fix version with:

```
devtools::install_github('ivyleavedtoadflax/rmd2md', ref='patch-1')
```

Then try using the function again, using just the bare 'figures' dir location.

**Comment by mammykins** [comment]
Did as instructed, package has RemoteRef: patch-1 in description so update seems to have applied.
Problem persists:
`rmd2md::rmd2md()`

`Error in value[[3L]](cond) : 
  Error produced running rmd2md():Error in doTryCatch(return(expr), name, parentenv, handler): Figures directory: figures/ does not exist!`

**Comment by ivyleavedtoadflax** [comment]
Hmm try specifying `base_dir/figures`

**Comment by mammykins** [comment]
No workie.

**Comment by ivyleavedtoadflax** [comment]
Roger, I'll make a real fix.

**Comment by ivyleavedtoadflax** [comment]
There is a test for this, which passes on linux. @mammykins can you download the package as a zip, unzip it somewhere, and then run the `tests/testthat.R` script. This will try to run a series of tests - would be interesting to see what passes and fails.

Also you might try putting a fully qualified link from `C:/...` - not sure what this will like on windows - just start at the root and use tab to auto complete.

**Comment by mammykins** [comment]
`rmd2md(path_site = "C:/Users/mammykins/Documents/GitHub/machinegurning.github.io/", url_images = "figures")`
Removing the backslash from the `url_images = "figures/"` default argument seemed to do the trick!

**Comment by ivyleavedtoadflax** [comment]
Yes I need to wrap the default location so that it is system specific. Can you confirm whether you used version `v0.1.0` or from `patch-1`? Would be good to incorporate this fix into `master`, but i don't have a windows system to test on.
