### ISSUE TITLE
rmd2md() fails on warning

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [ivyleavedtoadflax/rmd2md#3]
Warnings should be reported, but should not cause compilation to fail.

e.g. when running on https://github.com/machinegurning/machinegurning.github.io/_rmd/2016-10-23-kaggle_ames_house_prices.Rmd

```
Warning message:
In value[[3L]](cond) :
  Warning produced running rmd2md():simpleWarning: replacing previous import by 'ggplot2::unit' when loading 'extracat'
```

**Comment by ivyleavedtoadflax** [comment]
This may have been the problem you were experiencing @mammykins?

**Comment by mammykins** [comment]
No, but I have fixed it. I think it was due to local corrupted version of `knitr`. Reinstalling packages sorted it out.

**Comment by ivyleavedtoadflax** [comment]
Solved by suppressing warnings in `rmd2md()` (https://github.com/ivyleavedtoadflax/rmd2md/commit/3fa654134df7d86a417e531b038e8021c5f59491).
