### ISSUE TITLE
Current version not working due to default figures directory not being found

### ISSUE THREAD

**Issue by mammykins** [ivyleavedtoadflax/rmd2md#8]
I set wd to "C:/Users/mammykins/Documents/GitHub/machinegurning.github.io"

I run the latest version of `rmd2md::rmd2md()`

Produces this error:

Error in value[[3L]](cond) : 
  Error produced running rmd2md():Error in withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")): Figures directory: ./ does not exist!

As a hack I looked up the figure dir name, using `list.dirs()`: "./figures"

> rmd2md::rmd2md(figures = "./figures")  #  this runs!
47 files found in input folder.
Checking each file and processing if status: process

Thus if I insert this argument into the function it does work but puts the figures in the base directory, with the R-chunk name prefixed with figures, e.g., "figures2017-01-11-barplot". To fix this I moved renamed and moved these files into the figures dir manually. I then renamed the call to the figures in the post with the correct figure names.

It also produced a bunch of stuff in cache and didn't wipe it.

**Comment by ivyleavedtoadflax** [comment]
I thought I had fixed this. Are you sure you are using the latest commit?

**Comment by ivyleavedtoadflax** [comment]
Ok had another look at this. The new behaviour is that you have to specify a location for the figures, which should be `figures`, but I am implementing a fix in #9 to stop it from throwing the `./ does not exist error.`

It's basically caused by differences in the way you refer to locations in windows and linux.
